"""Constants."""

ROWS = 15
COLUMNS = 15
TILE_SIZE = 48

SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLUMNS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

# Turret constants.
# ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
